name: backend

on:
  pull_request

jobs:
    run-tests:
        runs-on: ubuntu-latest
        services:
            mongodb:
                image: mongo:latest
                ports:
                    - 27018:27017
                env:
                    MONGO_INITDB_ROOT_USERNAME: root
                    MONGO_INITDB_ROOT_PASSWORD: example
            
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Cache dependency
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/backend/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.13.2'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r backend/requirements.txt

            - name: Run integration tests
              run: |
                cd backend
                python manage.py test product.tests.integration.test_product
                python manage.py test product.tests.integration.test_category
            
            - name: Run unit tests
              run: |
                cd backend
                python manage.py test product.tests.unit.test_service

